CREATE DATABASE IF NOT EXISTS `todo`;
CREATE TABLE IF NOT EXISTS `todo`.`todo`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` TEXT NULL DEFAULT NULL,
    `is_end` BOOLEAN NOT NULL DEFAULT FALSE,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
);
