version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - "./:/var/www/html"
    ports:
      - 8030:80
    links:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 8031:3306
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8032:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
    links:
      - mysql
